### ISSUE TITLE
Add `pluralize` support

### ISSUE THREAD

**Issue by martin-damien** [martin-damien/babel#9]
Add an elegant way to support pluralization.

First test could be done with:

http://fr.wikipedia.org/wiki/Pluriels_irr%C3%A9guliers_en_fran%C3%A7ais
- Exceptions in base rule
- Complete rewrite of some words

**Comment by martin-damien** [comment]
I should take a look at how it is done in other libs...

**Comment by martin-damien** [comment]
http://unicode.org/repos/cldr-tmp/trunk/diff/supplemental/language_plural_rules.html

**Comment by alerque** [comment]
Perhaps of interest to you as a developer trying to implement this I've started setting up a Lua repository [`cldr-lua`](https://github.com/alerque/cldr-lua) with Unicode CLDR data to make downstream projects job easier. If you have any input into how to arrange that data in a way that would be useful to Lua projects feel free to speak up in issues there.

My own use case for this is for [`fluent-lua`](https://github.com/alerque/fluent-lua), a Lua implementation of [Project Fluent](https://projectfluent.org/). This covers many of the same features of this project but using FTL syntax as source, supporting the full array of it's features, and being more general purpose.

**Comment by ghost** [comment]
Thank you for your interest, but I do not have the time to maintain this project anymore.

I invite you to fork it if you want to make some changes.
